# Please refer to https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

global:
  appVersion: 3.6.1
  testVersion: 3.6.1

image:
  repository: artifactory.algol60.net/csm-docker/stable/cray-capmc
  pullPolicy: IfNotPresent

tests:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/cray-capmc-hmth-test
    pullPolicy: IfNotPresent

hms_ca_uri: ""

cray-service:
  type: "Deployment"
  nameOverride: "cray-capmc"
  fullnameOverride: "cray-capmc"
  replicaCount: 3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - cray-capmc
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
    type: RollingUpdate
  containers:
    cray-capmc:
      name: "cray-capmc"
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-capmc
      ports:
        - name: http
          containerPort: 27777
      env:
        - name: HSM_URL
          value: "http://cray-smd"
        - name: PCS_URL
          value: "http://cray-power-control"
        - name: CAPMC_CONFIG
          value: "/usr/local/etc/capmc-service/config.toml"
        - name: VAULT_ADDR
          value: "http://cray-vault.vault:8200"
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: CAPMC_CA_URI
          valueFrom:
            configMapKeyRef:
              name: capmc-cacert-info
              key: CA_URI
      livenessProbe:
        httpGet:
          port: 27777
          path: /capmc/v1/liveness
        initialDelaySeconds: 10
        periodSeconds: 20
      readinessProbe:
        httpGet:
          port: 27777
          path: /capmc/v1/readiness
        initialDelaySeconds: 5
        periodSeconds: 60
      resources:
        limits:
          cpu: "10"
          memory: 2Gi
        requests:
          cpu: "2"
          memory: 128Mi
      volumeMounts:
        - name: cray-capmc-config-vol
          mountPath: /usr/local/etc/capmc-service/config.toml
          readOnly: true
          subPath: config.toml
        - name: cray-pki-cacert-vol
          mountPath: /usr/local/cray-pki
  volumes:
    cray-capmc-config-vol:
      name: cray-capmc-config-vol
      configMap:
        name: cray-capmc-configuration
    cray-pki-cacert-vol:
      name: cray-pki-cacert-vol
      configMap:
        name: cray-configmap-ca-public-key

  ingress:
    enabled: true
    uri: " "
    prefix: /apis/capmc
